---
title: "Relatório <br>Infrequência escolar."
output:
 html_document:
  theme:
   version: 4 
   bootswatch: cerulean
params:
  data: !r NA
  municipiopoly: !r NA
  cid10: !r NA
  periodo: !r NA
---
<!--
<script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js"
          integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+"
           crossorigin="anonymous"></script>
--> 
```{r setup, include=FALSE}
# determine if running in Shiny or not
is_in_shiny <- if(is.null(shiny::getDefaultReactiveDomain())) FALSE else TRUE
if (is_in_shiny == TRUE) shiny::incProgress(amount = 20, message = "Preparando")

knitr::opts_chunk$set(echo = F, warning = FALSE, include = T,dev = c('svg'))
library('summaryBox')
library('kableExtra')
library('ggplot2')

theme_set(theme_minimal())


```

```{r preparacao, include=FALSE}
if (is_in_shiny == TRUE) shiny::incProgress(amount = 20, message = "Preparando...")
 dados_relatorio <- params$data
 dados_relatorio$semana <- cut(dados_relatorio$falta_7, breaks = '2 weeks')
 municipiopoly <- params$municipiopoly
 categoria_falta <- params$categoria_falta


 municipio_sf <- sf::st_as_sf(municipiopoly)
 
 #add em 03-nov-2022
 #funcao para label de quinzena
 func_semana <- function(x,y){
                 label <- NULL
                 x <- format(as.Date(levels(x)), '%d-%m-%Y')
                 ultimo <- format(max(y, na.rm = T), '%d-%m-%Y')
                 for(i in seq_along(x)){
                     label[i] <- paste0(x[i], ' à\n',x[i+1])
                     if(i == length(x)){
                     label[i] <- paste0(x[i], ' à\n',ultimo)     
                          }
                     }
                label
                         }
 
```

<br>

<span style = "font-size: 20pt;"> Período de análise: `r min(dados_relatorio$falta_7, na.rm = T)` à `r max(dados_relatorio$falta_7, na.rm = T)`

```{r box}
summaryBox("Total de estudantes", nrow(dados_relatorio), width = 12, style = 'info')
```

<br>

## Série temporal das informações

```{r serie_dados, fig.align='center' , fig.width = 11 }

 #série temporal
 serie <- with(dados_relatorio, as.data.frame(table(semana)) )
 label <- func_semana(serie$semana, dados_relatorio$falta_7)
 
 ggplot(serie, aes(x = semana, y = Freq)) +
 geom_col(fill = '#269CEA') +
 theme(legend.position = 'bottom',axis.text.x = element_text(angle=45)) +
 xlab('Semana') + ylab('Quantidade de alunos') +
 scale_x_discrete(labels = label)

```

## Localidade das ocorrências

<div class = "row">
<div class = "col-md-6">
### Ocorrência<br> das faltas

```{r mapa, }
 qtde_infreq <- with(dados_relatorio, as.data.frame(table(municipio)))
 quantis <- quantile(c(min(qtde_infreq[,2]), max(qtde_infreq[,2]))) %>% ceiling
 if(any(duplicated(quantis))){
    label <- paste0(quantis[1],'-',quantis[5])
    qtde_infreq$faixa <- as.factor(label)
    }else{
 label <- NULL
 for(i in 1:4){
     label[i] <- paste0(quantis[i],'-',quantis[i+1]-1)
     if(i == 4){label[i] <- paste0(quantis[i],'-',quantis[i+1])}}
 
 qtde_infreq$faixa <- cut(qtde_infreq[,2], breaks = quantile(c(min(qtde_infreq[,2]), max(qtde_infreq[,2]))), 
                         include.lowest = T, labels = label)
         } 
                         
 mapa_infreq <- left_join(municipio_sf, qtde_infreq, by = c('Municipio' = 'municipio'))

 ggplot(mapa_infreq) +
 geom_sf(aes(fill = faixa)) +
 scale_fill_manual(values = c('#bdd7e7','#6baed6','#3182bd','#08519c'),
                   na.translate = F, name = 'Quantidade de\nAlunos') +
 theme(legend.position = 'bottom', axis.text.x = element_blank(), axis.text.y = element_blank(),
       axis.ticks.x=element_blank(), axis.ticks.y=element_blank(), panel.grid = element_blank())

```
</div>

<div class = "col-md-6">
### Tabela dos municípios

```{r tabela_municipio, }

tabela <- with(dados_relatorio, as.data.frame(table(municipio)))
tabela <- arrange(tabela, desc(Freq))
names(tabela) <- c('Município', 'Qtde')

knitr::kable(tabela)   %>%
kable_styling(bootstrap_options = c('hover', 'striped')  )  %>%
  scroll_box(width = "100%", height = "450px")

```

</div>
</div> <!--end div duas colunas -->

<br>

## Estatísticas descritivas

<br>

<div class = "row">
<div class = "col-md-6">

### Média de frequência entre as faltas

```{r media_falta,  }
 falta <- dados_relatorio[,c('falta_1','falta_2','falta_3','falta_4',
                   'falta_5','falta_6','falta_7')]
 faltai <- sapply(1:6, function(x){abs(falta[,x+1] - falta[,x])}) %>%
           as.data.frame
           
 names(faltai) <- c('Dias 1-2', 'Dias 2-3',
                   'Dias 3-4', 'Dias 4-5',
                   'Dias 5-6', 'Dias 6-7')
                   

 faltai <- data.table::melt(faltai)
            
 ggplot(faltai, aes(x=as.factor(variable), y=value)) + 
    geom_boxplot(fill='#269CEA', alpha=0.4) + 
    xlab("Faltas") + ylab('Dias de presença')    
 
```

</div> 

<div class = "col-md-6">

### Anos escolares

```{r serie_falta, }

 tabela <- factor(dados_relatorio$serie, levels = educ_series)

 tabela <- as.data.frame(table(tabela))
 tabela$Freq[tabela$Freq == 0] <- NA

ggplot(tabela, aes(x = tabela, y = Freq)) + 
geom_col(fill = '#269CEA') +
geom_text(aes(label = Freq),position = position_dodge(),hjust = 0) + 
 coord_flip() +
 xlab('Ano') + ylab('Quantidade')

```


</div> 
 </div> <!-- end 2 colunas -->

<br>

### Possíveis causas

<br>

<div class = 'row'>
<div class = "col-md-6">
#### Causa Principal

```{r causa_principal }
 tabela <- with(dados_relatorio, as.data.frame(table(possiveis_causas_principal)))
 tabela[,1] <- as.character(levels(tabela[,1])[tabela[,1]])
 
 tabela <- arrange(tabela, desc(Freq))
 
 ggplot(tabela, aes(x = reorder(possiveis_causas_principal, Freq), y = Freq)) + 
 geom_col(fill = '#269CEA') +
 geom_text(aes(label = Freq),position = position_dodge(),hjust = 0) + 
 coord_flip() +
 xlab('Causas') + ylab('Quantidade')

```
</div>                                 

<div class = "col-md-6">
#### Outras causas

```{r outras_causas }
 tabela <- with(dados_relatorio, as.data.frame(table(possiveis_causas)))
 tabela[,1] <- as.character(levels(tabela[,1])[tabela[,1]])
 
 tabela <- arrange(tabela, desc(Freq))
 
 ggplot(tabela, aes(x = reorder(possiveis_causas, Freq), y = Freq)) + 
 geom_col(fill = '#269CEA') +
 geom_text(aes(label = Freq),position = position_dodge(),hjust = 0) + 
 coord_flip() +
 xlab('Possíveis\ncausas') + ylab('Quantidade')

```
</div>
</div> <!--end duas colunas--> 

<br>


<div class = 'row'>
<div class = "col-md-6">
#### Sexo

```{r sexo }
 tabela <- with(dados_relatorio, as.data.frame(table(sexo)))
 if(nrow(tabela) == 0){NULL}else{
 levels(tabela$sexo)  <- c('Masculino', 'Feminino', 'Não\nse aplica')
 tabela$Freq[tabela$Freq == 0] <- NA 
 tabela$prop <- with(tabela, Freq*100/sum(Freq, na.rm = T))
 tabela$ypos <- with(tabela, cumsum(prop) - 0.5*prop)

 ggplot(tabela, aes(x = sexo, y = Freq)) +
 geom_col(fill = '#269CEA') +
 geom_text(aes(label = Freq),position = position_stack(vjust = .5)) + 
 #coord_flip() +
 xlab('Sexo') + ylab('Quantidade')}

```
</div>
</div> <!--end duas colunas--> 
 <br>
