---
title: "Relatório Operacional:<br>Infrequência escolar."
output:
 html_document:
  theme:
   version: 4 
   bootswatch: cerulean
params:
  data: !r NA
  municipiopoly: !r NA
  cid10: !r NA
  periodo: !r NA
---
<!--
<script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js"
          integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+"
           crossorigin="anonymous"></script>
-->
```{r setup, include=FALSE}
# determine if running in Shiny or not
 is_in_shiny <- if(is.null(shiny::getDefaultReactiveDomain())) FALSE else TRUE
 if (is_in_shiny == TRUE) shiny::incProgress(amount = 20, message = "Preparando")

 knitr::opts_chunk$set(echo = F, warning = FALSE, message = F, include = T,dev = c('svg'))
 library('summaryBox')
 library('kableExtra')

 municipio_sf <- sf::st_as_sf(params$municipiopoly)

 dados_relatorio <- params$data
 dias <- seq(params$periodo[2]-27,params$periodo[2], 'day' )
 periodo <- data.frame(dias,
            semana = cut(dias, breaks = '7 days', 
                label = c('Semana 3', 'Semana 2', 'Semana 1', "Semana 0"))
                )
 dados_relatorio <- subset(dados_relatorio, falta_7 %in% dias)
 dados_relatorio <- left_join(dados_relatorio, periodo, by = c('falta_7' = 'dias'))
 
 #criaçao de variável apenas para a análise da ultima quinzena
 dados_relatorio$quinzena <- with(dados_relatorio, ifelse(semana == 'Semana 1', 'Semana Anterior',
                              ifelse(semana == 'Semana 0', 'Semana Atual',NA))) %>%
                              factor(., levels = c('Semana Anterior', "Semana Atual"))
  mapa_vazio <- 
 ggplot(municipio_sf) +
 geom_sf() +
 theme(legend.position = 'bottom', axis.text.x = element_blank(), axis.text.y = element_blank(),
       axis.ticks.x=element_blank(), axis.ticks.y=element_blank(), panel.grid = element_blank())
```
<br>

<span style = "font-size: 20pt;"> Período de análise: `r max(dias) - 6` à `r max(dias)` </span>


<div class = "row">
<div class = "col-md-4">
```{r box_0}
dadoi <- table(dados_relatorio$semana)
dadoii <- round((dadoi[4]/dadoi[3] - 1)*100,2)
if(is.nan(dadoii)){dadoii <- 0}
if(dadoii > 0){argumento <- c('fas fa-arrow-up', 'info')}else{argumento <- c('fas fa-arrow-down', 'danger')}
if(dadoii == 0){argumento <- c('fas fa-xmark', 'info')}
summaryBox("Estudantes faltantes\n (Semana 0)", paste0(dadoi[4], ' (',dadoii,'%)'), width = NULL, icon = argumento[1], style = argumento[2])

dadoii <- round((dadoi[3]/dadoi[2] - 1)*100,2)
if(is.nan(dadoii)){dadoii <- 0}
if(dadoii > 0){argumento <- c('fas fa-arrow-up', 'info')}else{argumento <- c('fas fa-arrow-down', 'danger')}
if(dadoii == 0){argumento <- c('fas fa-xmark', 'info')}

summaryBox("Estudantes faltantes\n (Semana 1)", paste0(dadoi[3], ' (',dadoii,'%)'), width = NULL, icon = argumento[1], style = argumento[2])

dadoii <- round((dadoi[2]/dadoi[1] - 1)*100,2)
if(is.nan(dadoii)){dadoii <- 0}
if(dadoii > 0){argumento <- c('fas fa-arrow-up', 'info')}else{argumento <- c('fas fa-arrow-down', 'danger')}
if(dadoii == 0){argumento <- c('fas fa-xmark', 'info')}
summaryBox("Estudantes faltantes\n (Semana 2)", paste0(dadoi[2], ' (',dadoii,'%)'), width = NULL, icon = argumento[1], style = argumento[2])

summaryBox("Estudantes faltantes\n (Semana 3)", paste0(dadoi[1]), width = NULL, icon = 'fas fa-comments', style = 'primary')

```

</div>

<div class = "col-md-8">
```{r serie_dados, }

 #série temporal
 dadoi <- as.data.frame(dadoi)
 if(max(dadoi[,2]) %% 2 == 0){escala <- 0:(max(dadoi[,2]))}
 if(max(dadoi[,2]) %% 2 == 1){escala <- 0:(max(dadoi[,2])+1)}
 dadoi[dadoi$Freq == 0, 'Freq'] <- NA
 
 ggplot(dadoi, aes(x = Var1, y = Freq)) +
 geom_col(fill = '#269CEA') +
 theme(legend.position = 'bottom') + 
 scale_y_continuous(limits = c(min(escala), max(escala)),
                    breaks = escala) +
 geom_text(aes(label = Freq, y = Freq + .1),position = position_dodge(),hjust = 0, vjust = 0) +
 xlab('') + ylab('Registros') +
 labs(title = 'Série\nfaltas')

```


</div>
</div>

<br>

## Análise comparativa das últimas 2 semanas.
<br>

<div class = "row">
<div class = "col-md-6" style = "border-right: 1px solid black;">
### Semana<br> anterior

```{r mapa_1, }
 if(nrow(dados_relatorio[dados_relatorio$semana == 'Semana 1',]) == 0){mapa_vazio + 
    labs(title = 'Município de\nocorrência')}else{
 qtde_falta <- with(dados_relatorio[dados_relatorio$semana == 'Semana 1',], as.data.frame(table(municipio)))
 quantis <- quantile(c(min(qtde_falta[,2]), max(qtde_falta[,2]))) %>% ceiling
 if(any(duplicated(quantis))){
    label <- paste0(quantis[1],'-',quantis[5])
    qtde_falta$faixa <- as.factor(label)
    }else{
 label <- NULL
 for(i in 1:4){
     label[i] <- paste0(quantis[i],'-',quantis[i+1]-1)
     if(i == 4){label[i] <- paste0(quantis[i],'-',quantis[i+1])}}
 
 qtde_falta$faixa <- cut(qtde_falta[,2], breaks = quantile(c(min(qtde_falta[,2]), max(qtde_falta[,2]))), 
                         include.lowest = T, labels = label)
         }
                          
 mapa_falta <- left_join(municipio_sf, qtde_falta, by = c('Municipio' = 'municipio'))

 ggplot(mapa_falta) +
 geom_sf(aes(fill = faixa)) +
 scale_fill_manual(values = c('#bdd7e7','#6baed6','#3182bd','#08519c'),
                   na.translate = F, name = 'Quantidade de\nRegistros') +
 theme(legend.position = 'bottom', axis.text.x = element_blank(), axis.text.y = element_blank(),
       axis.ticks.x=element_blank(), axis.ticks.y=element_blank(), panel.grid = element_blank()) +
 labs(title = 'Município de\nocorrência')
 }
```

</div>

<div class = "col-md-6">
### Semana<br> atual

```{r mapa_2, }
 if(nrow(dados_relatorio[dados_relatorio$semana == 'Semana 0',]) == 0){mapa_vazio + 
                                                labs(title = 'Município de\nocorrência')}else{
 qtde_falta <- with(dados_relatorio[dados_relatorio$semana == 'Semana 0',], as.data.frame(table(municipio)))
 quantis <- quantile(c(min(qtde_falta[,2]), max(qtde_falta[,2]))) %>% ceiling
 if(any(duplicated(quantis))){
    label <- paste0(quantis[1],'-',quantis[5])
    qtde_falta$faixa <- as.factor(label)
    }else{
 label <- NULL
 for(i in 1:4){
     label[i] <- paste0(quantis[i],'-',quantis[i+1]-1)
     if(i == 4){label[i] <- paste0(quantis[i],'-',quantis[i+1])}}
 
 qtde_falta$faixa <- cut(qtde_falta[,2], breaks = quantile(c(min(qtde_falta[,2]), max(qtde_falta[,2]))), 
                         include.lowest = T, labels = label)
         }
                          
 mapa_falta <- left_join(municipio_sf, qtde_falta, by = c('Municipio' = 'municipio'))

 ggplot(mapa_falta) +
 geom_sf(aes(fill = faixa)) +
 scale_fill_manual(values = c('#bdd7e7','#6baed6','#3182bd','#08519c'),
                   na.translate = F, name = 'Quantidade de\nRegistros') +
 theme(legend.position = 'bottom', axis.text.x = element_blank(), axis.text.y = element_blank(),
       axis.ticks.x=element_blank(), axis.ticks.y=element_blank(), panel.grid = element_blank()) +
 labs(title = 'Município de\nocorrência')
  }
```

</div>
</div>

<br>

<div class = "row">
<div class = "col-md-6" style = "border-right: 1px solid black;">

### Média de frequência entre as faltas

```{r media_falta,  }
 falta <- dados_relatorio[,c('falta_1','falta_2','falta_3','falta_4',
                   'falta_5','falta_6','falta_7', 'quinzena')]
 faltai <- purrr::map_df(split(falta, falta$quinzena), function(z){
                      if(nrow(z) == 0){z[1,] <- NA}
                      sapply(1:6, function(x){abs(z[,x+1] - z[,x])}) %>%
                      as.data.frame
                     }, .id = 'quinzena' )
 if(ncol(faltai) >2){
 #faltai <- faltai[,-8]          
 names(faltai)[2:7] <- c('Dias 1-2', 'Dias 2-3',
                   'Dias 3-4', 'Dias 4-5',
                   'Dias 5-6', 'Dias 6-7')}
                   

 faltai <- data.table::melt(faltai, id.vars = 'quinzena')
            
 ggplot(faltai, aes(x=variable, y=value)) + 
    geom_boxplot(aes(fill=quinzena), alpha=0.4) + 
    
    xlab("Faltas") + ylab('Dias de presença')   +
     scale_fill_manual(values = c('#184ED3', '#269CEA'), guide_legend(title = '')) +
 theme(legend.position = 'bottom') 
 
```

</div> 

<div class = "col-md-6">

### Anos escolares

```{r serie_falta, }

 tabela <- data.frame(tabela = factor(dados_relatorio$serie, levels = educ_series), quinzena = dados_relatorio$quinzena)

 tabela <- with(tabela,as.data.frame(table(tabela, quinzena)))
 tabela[tabela$Freq == 0,'Freq'] <- NA

 ggplot(tabela, aes(x = tabela, y = Freq)) + 
 geom_col(aes(fill=quinzena)) +
 geom_text(aes(label = Freq, group = quinzena),position = position_stack(vjust = .5)) + 
 coord_flip() +
 xlab('Ano') + ylab('Quantidade')  +
 scale_fill_manual(values = c('#184ED3', '#269CEA'), guide_legend(title = '')) +
 theme(legend.position = 'bottom') 

```


</div> 
 </div> <!-- end 2 colunas -->

<br>

### Possíveis causas

<br>

<div class = 'row'>
<div class = "col-md-6">
#### Causa Principal

```{r causa_principal }
 tabela <-  with(dados_relatorio, as.data.frame(table(possiveis_causas_principal, quinzena)))
 
 tabela <- arrange(tabela, desc(Freq))
 tabela[tabela$Freq == 0, 'Freq'] <- NA
 
 ggplot(tabela, aes(x = reorder(possiveis_causas_principal, Freq), y = Freq)) + 
 geom_col(aes(fill=quinzena)) +
 geom_text(aes(label = Freq, group = quinzena),position = position_stack(vjust = .5)) +
 coord_flip() +
 xlab('Causas') + ylab('Quantidade') +
 scale_fill_manual(values = c('#184ED3', '#269CEA'), guide_legend(title = '')) +
 theme(legend.position = 'bottom') 

```
</div>                                 

<div class = "col-md-6">

#### Outras causas

```{r outras_causas }
 tabela <-  with(dados_relatorio[dados_relatorio$possiveis_causas != '',], as.data.frame(table(possiveis_causas, quinzena)))
 
 if(sum(tabela$Freq) == 0){NULL}else{
 tabela <- arrange(tabela, desc(Freq))
 tabela[tabela$Freq == 0, 'Freq'] <- NA
 
 ggplot(tabela, aes(x = reorder(possiveis_causas, Freq), y = Freq)) + 
 geom_col(aes(fill=quinzena)) +
 geom_text(aes(label = Freq, group = quinzena),position = position_stack(vjust = .5)) +
 coord_flip() +
 xlab('Causas') + ylab('Quantidade') +
 scale_fill_manual(values = c('#184ED3', '#269CEA'), guide_legend(title = '')) +
 theme(legend.position = 'bottom')}

```
</div>
</div> <!--end duas colunas--> 

<br>


<div class = 'row'>
<div class = "col-md-6">
#### Sexo

```{r sexo }
  dadoi <- with(dados_relatorio[!is.na(dados_relatorio$quinzena),], as.data.frame(table(sexo)))
 if(nrow(dadoi) == 0){NULL}else{
 
 
 if(max(dadoi[,2]) %% 2 == 0){escala <- 0:(max(dadoi[,2]))}
 if(max(dadoi[,2]) %% 2 == 1){escala <- 0:(max(dadoi[,2])+1)}

 tabela <- with(dados_relatorio, as.data.frame(table(sexo, quinzena))) 
 tabela[tabela$Freq == 0,3] <- NA 
 levels(tabela$sexo)  <- c('Masculino', 'Feminino', 'Não\nse aplica')          

 ggplot(tabela, aes(x = sexo, y = Freq)) + 
 geom_col(aes(fill = quinzena), alpha = .7) +
 geom_text(aes(label = Freq),position = position_stack(vjust = .5)) + 
 coord_flip() +
 xlab('Sexo') + ylab('Quantidade')  +
 scale_fill_manual(values = c('#184ED3', '#269CEA', '26EAC9'), guide_legend(title = '')) +
 scale_y_continuous(limits = c(min(escala), max(escala)),
                    breaks = escala)   +
 theme(legend.position = 'bottom')
  }
```
</div>
</div> <!--end duas colunas--> 
 <br>