---
title: "Relatório <br>Mortalidade Infantil."
output:
 html_document:
  theme:
   version: 4 
   bootswatch: cerulean
params:
  data: !r NA
  municipiopoly: !r NA
  cid10: !r NA
  periodo: !r NA
---
<!--
<script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js"
          integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+"
           crossorigin="anonymous"></script>
--> 
```{r setup, include=FALSE}
# determine if running in Shiny or not
is_in_shiny <- if(is.null(shiny::getDefaultReactiveDomain())) FALSE else TRUE
if (is_in_shiny == TRUE) shiny::incProgress(amount = 20, message = "Preparando")

knitr::opts_chunk$set(echo = F, warning = FALSE, include = T,dev = c('svg'))
library('summaryBox')
library('kableExtra')
library('ggplot2')

theme_set(theme_minimal())


```

```{r preparacao, include=FALSE}
 if (is_in_shiny == TRUE) shiny::incProgress(amount = 20, message = "Preparando...")
 dados_relatorio <- params$data
 dados_relatorio$semana <- cut(dados_relatorio$dat_obito, breaks = '2 weeks')

 municipiopoly <- params$municipiopoly
 municipio_sf <- sf::st_as_sf(municipiopoly)
 
 #add em 03-nov-2022
 #funcao para label de quinzena
 func_semana <- function(x,y){
                 label <- NULL
                 x <- format(as.Date(levels(x)), '%d-%m-%Y')
                 ultimo <- format(max(y, na.rm = T), '%d-%m-%Y')
                 for(i in seq_along(x)){
                     label[i] <- paste0(x[i], ' à\n',x[i+1])
                     if(i == length(x)){
                     label[i] <- paste0(x[i], ' à\n',ultimo)     
                          }
                     }
                label
                         }
```


<br>

<span style = "font-size: 20pt;"> Período de análise: `r min(dados_relatorio$dat_obito, na.rm = T)` à `r max(dados_relatorio$dat_obito, na.rm = T)`

```{r box}
summaryBox("Óbitos totais", nrow(dados_relatorio), width = 12, style = 'info')
```

<br>

## Série temporal das informações

```{r serie_dados, fig.align='center', fig.width = 11 }

 #série temporal
 serie <- with(dados_relatorio, as.data.frame(table(semana)) )
 label <- func_semana(serie$semana, dados_relatorio$dat_obito)
 
 
 ggplot(serie, aes(x = semana, y = Freq)) +
 geom_col(fill = '#269CEA') +
 theme(legend.position = 'bottom',axis.text.x = element_text(angle=45)) +
 xlab('Quinzena') + ylab('Óbitos\nregistrados')  +
 scale_x_discrete(labels = label)

```

## Mapa dos óbitos

<div class = "row">
<div class = "col-md-6">
### Ocorrência<br> dos óbitos

```{r mapa, }
 qtde_obito <- with(dados_relatorio, as.data.frame(table(municipio)))
 quantis <- quantile(c(min(qtde_obito[,2]), max(qtde_obito[,2]))) %>% ceiling
 if(any(duplicated(quantis))){
    label <- paste0(quantis[1],'-',quantis[5])
    qtde_obito$faixa <- as.factor(label)
    }else{
 label <- NULL
 for(i in 1:4){
     label[i] <- paste0(quantis[i],'-',quantis[i+1]-1)
     if(i == 4){label[i] <- paste0(quantis[i],'-',quantis[i+1])}}
 
 qtde_obito$faixa <- cut(qtde_obito[,2], breaks = quantile(c(min(qtde_obito[,2]), max(qtde_obito[,2]))), 
                         include.lowest = T, labels = label)
         } 
                         
 mapa_obito <- left_join(municipio_sf, qtde_obito, by = c('Municipio' = 'municipio'))

 ggplot(mapa_obito) +
 geom_sf(aes(fill = faixa)) +
 scale_fill_manual(values = c('#bdd7e7','#6baed6','#3182bd','#08519c'),
                   na.translate = F, name = 'Quantidade de\nÓbitos') +
 theme(legend.position = 'bottom', axis.text.x = element_blank(), axis.text.y = element_blank(),
       axis.ticks.x=element_blank(), axis.ticks.y=element_blank(), panel.grid = element_blank())

```

<br>

```{r tabela_municipio_obito, }

tabela <- with(dados_relatorio, as.data.frame(table(municipio)))
tabela <- arrange(tabela, desc(Freq))
names(tabela) <- c('Município', 'Qtde')

knitr::kable(tabela)   %>%
kable_styling(bootstrap_options = c('hover', 'striped')  )  %>%
  scroll_box(width = "100%", height = "450px")

```

</div>

<div class = "col-md-6">

### Residência<br> do responsável

```{r mapa_resid, }
 qtde_obito <- with(dados_relatorio, as.data.frame(table(municipio_responsavel)))
 quantis <- quantile(c(min(qtde_obito[,2]), max(qtde_obito[,2])))  %>% ceiling
if(any(duplicated(quantis))){
    label <- paste0(quantis[1],'-',quantis[5])
    qtde_obito$faixa <- as.factor(label)
    }else{
 label <- NULL
 for(i in 1:4){
     label[i] <- paste0(quantis[i],'-',quantis[i+1]-1)
     if(i == 4){label[i] <- paste0(quantis[i],'-',quantis[i+1])}}
 
 qtde_obito$faixa <- cut(qtde_obito[,2], breaks = quantile(c(min(qtde_obito[,2]), max(qtde_obito[,2]))), 
                         include.lowest = T, labels = label)
         }
                         
 mapa_obito <- left_join(municipio_sf, qtde_obito, by = c('Municipio' = 'municipio_responsavel'))

 ggplot(mapa_obito) +
 geom_sf(aes(fill = faixa)) +
 scale_fill_manual(values = c('#bdd7e7','#6baed6','#3182bd','#08519c'),
                   na.translate = F, name = 'Quantidade de\nÓbitos') +
 theme(legend.position = 'bottom', axis.text.x = element_blank(), axis.text.y = element_blank(),
       axis.ticks.x=element_blank(), axis.ticks.y=element_blank(), panel.grid = element_blank())

```


<br>

```{r tabela_municipio_resid, }

tabela <- with(dados_relatorio, as.data.frame(table(municipio_responsavel)))
tabela <- arrange(tabela, desc(Freq))
names(tabela) <- c('Município', 'Qtde')

knitr::kable(tabela)   %>%
kable_styling(bootstrap_options = c('hover', 'striped')  )  %>%
  scroll_box(width = "100%", height = "450px")

```

</div>
</div> <!--end div duas colunas -->

<br>

## Estatísticas dos infantes
<div class = "row">
<div class = "col-md-6">

### Sexo

```{r sexo_infante, }

tabela <- with(dados_relatorio, as.data.frame(table(sexo)))
levels(tabela$sexo)  <- c('Masculino', 'Feminino')
tabela$Freq[tabela$Freq == 0] <- NA 
tabela$prop <- with(tabela, Freq*100/sum(Freq, na.rm = T))
tabela$ypos <- with(tabela, cumsum(prop) - 0.5*prop)

ggplot(tabela, aes(x = sexo, y = Freq)) +
geom_col(fill = '#269CEA') +
geom_text(aes(label = Freq),position = position_stack(vjust = .5)) + 
 #coord_flip() +
 xlab('Sexo') + ylab('Quantidade')
 
```

</div> 

<div class = "col-md-6">

### Idade

```{r idade_infante, }

dados_relatorio$idade_graf <- cut(floor(dados_relatorio$idade), breaks = c(0,1,30,365, Inf), 
                        labels = c('Menos 1 dia', 'Até 30 dias','Até 1 ano','> 1 ano'))

tabela <- with(dados_relatorio, as.data.frame(table(idade_graf)))

ggplot(tabela, aes(x = idade_graf, y = Freq)) + 
geom_col(fill = '#269CEA') +
geom_text(aes(label = Freq),position = position_dodge(),hjust = 0) + 
 coord_flip() +
 xlab('Faixa de\nidade') + ylab('Quantidade')

```


</div> 
 </div> <!-- end 2 colunas -->

<br>

### Cid Evitável
<br>
<div class = 'row'>
<div class = "col-md-3">
```{r cid_infante, }
 texto <- paste0(table(dados_relatorio$obt_evitavel)[1], ' (', round(table(dados_relatorio$obt_evitavel)[1]*100/nrow(dados_relatorio),1),'%)' )
 summaryBox("Óbitos evitáveis", texto, width  = NULL, style = 'info')

```
</div>                                 

<div class = "col-md-9">
```{r cid_tabela_infante, }
 tabela <- with(dados_relatorio, as.data.frame(table(cid_evitavel)))
 tabela <- left_join(tabela, cid_evitavel, by = c('cid_evitavel' = 'CID10'))
 tabela <- tabela[,c(1,3,2)]
names(tabela) <- c('Código', 'Descrição', 'Qtde')

knitr::kable(tabela)   %>%
kable_styling(bootstrap_options = c('hover', 'striped')  )   %>%
  scroll_box(width = "100%", height = "300px")

```
</div>
</div> <!--end duas colunas--> 

<br>

## Estatísticas do responsável

<div class = "row">
<div class = "col-md-6">

### Responsável

```{r responsavel, }
 tabela <- with(dados_relatorio, as.data.frame(table(responsavel)))

ggplot(tabela, aes(x = responsavel, y = Freq)) + 
geom_col(fill = '#269CEA') +
geom_text(aes(label = Freq),position = position_dodge(),hjust = 0) + 
 coord_flip() +
 xlab('Descrição do\nresponsável') + ylab('Quantidade')
  
```  

</div> 

<div class = "col-md-6">

### Idade

```{r idade_resp, }
idade_graf <- cut(floor(dados_relatorio$idade_responsavel), breaks = c(0,18,seq(30,70, 10), Inf), 
                        labels = c('0-17','18-29','30-39',
                                   '40-49','50-59','60-69','>70'))

tabela <- as.data.frame(table(idade_graf))

ggplot(tabela, aes(x = idade_graf, y = Freq)) + 
geom_col(fill = '#269CEA') +
geom_text(aes(label = Freq),position = position_dodge(),hjust = 0) + 
 coord_flip() +
 xlab('Faixa de\nidade') + ylab('Quantidade')
 
```

</div> 
 </div> <!-- end 2 colunas -->
 
<div class = "row">
<div class = "col-md-6">

### Situação conjugal

```{r sit_conjug, }
tabela <- factor(dados_relatorio$sit_conjungal, levels = c(1:6))
tabela <- as.data.frame(table(tabela))
tabela$sit_conjugal <- as.factor(c('Casado', 'Solteiro', 'Viúvo', 
                                    'Separado/divorciado', 'União estável', 'Ignorado') )
tabela$Freq[tabela$Freq == 0] <- NA
tabela$prop <- with(tabela, round(Freq*100/sum(Freq, na.rm = T),1)) %>% paste0(., '%')

ggplot(tabela, aes(x = sit_conjugal, y = Freq)) + 
geom_col(fill = '#269CEA') +
geom_text(aes(label = paste0(Freq, ' (',prop,')' )),position = position_dodge(),hjust = 1) + 
 coord_flip() +
 xlab('Situação\nconjugal') + ylab('Quantidade') 
```

</div> 

<div class = "col-md-6">

### Cor da pele

```{r pele, }
tabela <- factor(dados_relatorio$cor, levels = c(1:6))
tabela <- as.data.frame(table(tabela))
tabela$desc_cor <- as.factor(c('Branca' , 'Preta' , 'Amarela' , 'Parda' , 'Indígena', 'Ignorado'  ))
tabela$Freq[tabela$Freq == 0] <- NA
tabela$prop <- with(tabela, round(Freq*100/sum(Freq, na.rm = T),1)) %>% paste0(., '%')

ggplot(tabela, aes(x = desc_cor, y = Freq)) + 
geom_col(fill = '#269CEA') +
geom_text(aes(label = paste0(Freq, ' (',prop,')' )),position = position_dodge(),hjust = 1) + 
 coord_flip() +
 xlab('Cor\nda pele') + ylab('Quantidade') 
```

</div> 

</div> <!-- end 2 colunas -->


<div class = "row">
<div class = "col-md-6">

### Escolaridade

```{r escolaridade, }
tabela <- factor(dados_relatorio$escolaridade, levels = c(1:7))
tabela <- as.data.frame(table(tabela))
tabela$escolaridade <- as.factor(c('Sem escolaridade' ,'Fundamental I',
                         'Fundamental II' , 'Ensino médio','Superior Incompleto', 'Superior Completo', 'Ignorado' ))
tabela$Freq[tabela$Freq == 0] <- NA
tabela$prop <- with(tabela, round(Freq*100/sum(Freq, na.rm = T),1)) %>% paste0(., '%')

ggplot(tabela, aes(x = escolaridade, y = Freq)) + 
geom_col(fill = '#269CEA') +
geom_text(aes(label = paste0(Freq, ' (',prop,')' )),position = position_dodge(),hjust = 1) + 
 coord_flip() +
 xlab('Escolaridade') + ylab('Quantidade') 
```

</div> 

<div class = "col-md-6">

### 

```{r filhos, }
tabela <- with(dados_relatorio, as.data.frame(table(qtde_filhos)))

ggplot(tabela, aes(x = qtde_filhos, y = Freq)) + 
geom_col(fill = '#269CEA') +
geom_text(aes(label = Freq),position = position_dodge(),hjust = 1) + 
 coord_flip() +
 xlab('Quantidade\nde filhos') + ylab('Quantidade') 
```

</div> 

</div> <!-- end 2 colunas -->
